# Generated by Django 5.0.7 on 2024-08-08 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('usuario', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='HorasMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('operario', models.CharField(max_length=40)),
                ('horas_del_mes', models.IntegerField()),
                ('horas_trabajadas', models.IntegerField()),
                ('horas_extras', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('seg_nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(max_length=20)),
                ('seg_apellido', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaTra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reloj_fichador.operario')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reloj_fichador.operario')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reloj_fichador.operario')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaTra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reloj_fichador.operario')),
            ],
        ),
    ]
