# Generated by Django 5.0.7 on 2024-08-20 14:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del horario (por ejemplo, Turno Mañana)', max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Licencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('certificado', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reloj_fichador.horario')),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('seg_nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(max_length=20)),
                ('seg_apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('areas', models.ManyToManyField(to='reloj_fichador.area')),
            ],
        ),
        migrations.CreateModel(
            name='Horas_trabajadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas_trabajadas', models.DurationField(default=datetime.timedelta)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reloj_fichador.operario')),
            ],
            options={
                'verbose_name': 'Horas normales',
                'verbose_name_plural': 'Horas normales',
            },
        ),
        migrations.CreateModel(
            name='Horas_totales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_actual', models.CharField(max_length=20)),
                ('horas_totales', models.DurationField(default=datetime.timedelta)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reloj_fichador.operario')),
            ],
            options={
                'verbose_name': 'Horas totales',
                'verbose_name_plural': 'Horas totales',
            },
        ),
        migrations.CreateModel(
            name='Horas_feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas_feriado', models.DurationField(default=datetime.timedelta)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reloj_fichador.operario')),
            ],
            options={
                'verbose_name': 'Horas feriado',
                'verbose_name_plural': 'Horas feriado',
            },
        ),
        migrations.CreateModel(
            name='Horas_extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('horas_extras', models.DurationField(default=datetime.timedelta)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reloj_fichador.operario')),
            ],
            options={
                'verbose_name': 'Horas extras',
                'verbose_name_plural': 'Horas extras',
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('hora_fichada', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida_transitoria', 'Salida Transitoria'), ('entrada_transitoria', 'Entrada Transitoria'), ('salida', 'Salida')], max_length=20)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reloj_fichador.operario')),
            ],
        ),
    ]
