# Generated by Django 5.0.7 on 2024-08-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='horario',
        ),
        migrations.AddField(
            model_name='area',
            name='horarios',
            field=models.ManyToManyField(to='reloj_fichador.horario'),
        ),
    ]
