# Generated by Django 5.0.7 on 2024-08-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
