# Generated by Django 5.0.7 on 2024-08-14 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0002_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('hora_fichada', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('sal_transitoria', 'Salida Transitoria'), ('ent_transitoria', 'Entrada Transitoria'), ('salida', 'Salida')], max_length=20)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reloj_fichador.operario')),
            ],
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='operario',
        ),
        migrations.RemoveField(
            model_name='entradatra',
            name='operario',
        ),
        migrations.DeleteModel(
            name='HorasMensual',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='operario',
        ),
        migrations.RemoveField(
            model_name='salidatra',
            name='operario',
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.DeleteModel(
            name='EntradaTra',
        ),
        migrations.DeleteModel(
            name='Salida',
        ),
        migrations.DeleteModel(
            name='SalidaTra',
        ),
    ]
