# Generated by Django 5.0.7 on 2024-08-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0004_remove_horas_extras_mes_horas_extras_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='origen_fichada',
            field=models.CharField(default='Auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='hora_fichada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
