# Generated by Django 5.0.7 on 2024-08-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0005_registrodiario_origen_fichada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
