# Generated by Django 5.0.7 on 2024-08-24 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0006_operario_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horas_totales',
            old_name='horas_totales',
            new_name='horas_extras',
        ),
        migrations.AddField(
            model_name='horas_totales',
            name='horas_feriado',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='horas_totales',
            name='horas_nocturnas',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='horas_totales',
            name='horas_normales',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
