# Generated by Django 5.0.7 on 2024-08-24 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0007_rename_horas_totales_horas_totales_horas_extras_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horas_trabajadas',
            options={'verbose_name': 'Horas normales y nocturnas', 'verbose_name_plural': 'Horas normales y nocturnas'},
        ),
        migrations.AddField(
            model_name='horas_trabajadas',
            name='horas_nocturnas',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
