# Generated by Django 5.0.7 on 2024-08-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0008_alter_horas_trabajadas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horas_trabajadas',
            options={'verbose_name': 'Horas normales', 'verbose_name_plural': 'Horas normales'},
        ),
        migrations.AddField(
            model_name='operario',
            name='licencias',
            field=models.FileField(blank=True, null=True, upload_to='licencias/'),
        ),
    ]
