# Generated by Django 5.0.7 on 2024-08-26 10:34

import apps.reloj_fichador.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0009_alter_horas_trabajadas_options_operario_licencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operario',
            name='licencias',
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='licencias/', validators=[apps.reloj_fichador.models.validate_file_extension])),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='reloj_fichador.operario')),
            ],
        ),
    ]
