# Generated by Django 5.0.7 on 2024-08-26 11:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0010_remove_operario_licencias_licencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado_asistencia', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], default='Ausente', max_length=10)),
                ('estado_justificacion', models.CharField(blank=True, choices=[('Justificado', 'Justificado'), ('No Justificado', 'No Justificado')], max_length=15, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reloj_fichador.operario')),
            ],
            options={
                'unique_together': {('operario', 'fecha')},
            },
        ),
    ]
