# Generated by Django 5.0.7 on 2024-08-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0011_registroasistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado_asistencia',
            field=models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente')], default='ausente', max_length=10),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado_justificacion',
            field=models.CharField(blank=True, choices=[('justificado', 'Justificado'), ('no justificado', 'No Justificado')], max_length=15, null=True),
        ),
    ]
