# Generated by Django 5.0.7 on 2024-08-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0012_alter_registroasistencia_estado_asistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado_asistencia',
            field=models.CharField(choices=[('presente', '✅ Presente'), ('ausente', '❌ Ausente')], default='ausente', max_length=10),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado_justificacion',
            field=models.BooleanField(default=False, help_text='Marcar como justificado (1) o no justificado (0)'),
        ),
    ]
