# Generated by Django 5.0.7 on 2024-08-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0013_licencia_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Licencias',
        ),
        migrations.AddField(
            model_name='licencia',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licencia',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
