# Generated by Django 5.0.7 on 2024-09-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0017_registrodiario_inconsistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodiario',
            name='inconsistencia',
            field=models.BooleanField(choices=[(True, 'Inconsistencia'), (False, '')], default=False),
        ),
    ]
