# Generated by Django 5.1.4 on 2024-12-11 15:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0018_alter_registrodiario_inconsistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOperario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dni', models.IntegerField(db_index=True)),
                ('nombre', models.CharField(max_length=20)),
                ('seg_nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(max_length=20)),
                ('seg_apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso_empresa', models.DateField(blank=True, null=True)),
                ('titulo_tecnico', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('foto', models.TextField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical operario',
                'verbose_name_plural': 'historical operarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRegistroDiario',
            fields=[
                ('id_registro', models.IntegerField(blank=True, db_index=True)),
                ('hora_fichada', models.DateTimeField(blank=True, null=True)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida_transitoria', 'Salida Transitoria'), ('entrada_transitoria', 'Entrada Transitoria'), ('salida', 'Salida')], max_length=20)),
                ('origen_fichada', models.CharField(default='Auto', max_length=10)),
                ('inconsistencia', models.BooleanField(choices=[(True, 'Inconsistencia'), (False, '')], default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical registro diario',
                'verbose_name_plural': 'historical registro diarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='operario',
            index=models.Index(fields=['apellido'], name='reloj_ficha_apellid_2940c9_idx'),
        ),
        migrations.AddIndex(
            model_name='operario',
            index=models.Index(fields=['dni'], name='reloj_ficha_dni_b631b6_idx'),
        ),
        migrations.AddIndex(
            model_name='registrodiario',
            index=models.Index(fields=['operario'], name='reloj_ficha_operari_7b299b_idx'),
        ),
        migrations.AddIndex(
            model_name='registrodiario',
            index=models.Index(fields=['hora_fichada'], name='reloj_ficha_hora_fi_0ff313_idx'),
        ),
        migrations.AddField(
            model_name='historicaloperario',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalregistrodiario',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalregistrodiario',
            name='operario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reloj_fichador.operario'),
        ),
    ]
