# Generated by Django 5.1.4 on 2024-12-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0019_historicaloperario_historicalregistrodiario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrodiario',
            name='valido',
            field=models.BooleanField(default=True, help_text='Indica si el registro es válido.'),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='valido',
            field=models.BooleanField(default=True, help_text='Indica si el registro es válido.'),
        ),
    ]
