# Generated by Django 5.1.4 on 2024-12-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0020_historicalregistrodiario_valido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrodiario',
            name='descripcion_inconsistencia',
            field=models.TextField(blank=True, help_text='Descripción de la inconsistencia, si existe.', null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='descripcion_inconsistencia',
            field=models.TextField(blank=True, help_text='Descripción de la inconsistencia, si existe.', null=True),
        ),
    ]
