# Generated by Django 5.1.4 on 2024-12-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0021_historicalregistrodiario_descripcion_inconsistencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horas_trabajadas',
            options={},
        ),
        migrations.AddField(
            model_name='historicalregistrodiario',
            name='dif_entrada_salida',
            field=models.DurationField(blank=True, help_text='Diferencia de tiempo entre la última entrada y esta salida', null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='dif_entrada_salida',
            field=models.DurationField(blank=True, help_text='Diferencia de tiempo entre la última entrada y esta salida', null=True),
        ),
    ]
