# Generated by Django 5.1.4 on 2024-12-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0025_rename_horas_trabajadas_horas_trabajadas_horas_normales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horas_trabajadas',
            options={'verbose_name': 'Horas trabajadas', 'verbose_name_plural': 'Horas trabajadas'},
        ),
    ]
