# Generated by Django 5.1.4 on 2025-05-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0026_alter_horas_trabajadas_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRedondeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_redondeo_baja', models.PositiveSmallIntegerField(default=15, help_text='Minutos máximos para redondear hacia la hora en punto. Ejemplo: con 15, 09:14 se redondea a 09:00.')),
                ('minutos_redondeo_media', models.PositiveSmallIntegerField(default=45, help_text='Minutos máximos para redondear a la media hora. Ejemplo: con 45, 09:30 a 09:44 se redondea a 09:30.')),
            ],
            options={
                'verbose_name': 'Configuración de Redondeo',
                'verbose_name_plural': 'Configuración de Redondeo',
            },
        ),
    ]
