# Generated by Django 5.1.4 on 2025-03-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0026_alter_horas_trabajadas_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaFeriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(help_text='Descripción o nombre del feriado', max_length=100)),
                ('es_laborable', models.BooleanField(default=False, help_text='Indica si se trabaja en este feriado')),
            ],
            options={
                'verbose_name': 'Día feriado',
                'verbose_name_plural': 'Días feriados',
                'ordering': ['-fecha'],
            },
        ),
    ]
