# Generated by Django 5.1.4 on 2025-08-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0027_configuracionredondeo_configuracionredondeosalida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': '📊 Reportes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reloj_fichador.registrodiario',),
        ),
    ]
