# Generated by Django 5.1.4 on 2025-05-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0027_configuracionredondeo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRedondeoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_redondeo_salida', models.PositiveSmallIntegerField(default=0, help_text='Minutos a los que se redondea la salida hacia abajo. Ejemplo: con 0, 17:23 se redondea a 17:00.')),
            ],
            options={
                'verbose_name': 'Configuración de Redondeo de Salida',
                'verbose_name_plural': 'Configuración de Redondeo de Salida',
            },
        ),
    ]
