# Generated by Django 5.1.4 on 2025-08-11 14:10

import apps.reloj_fichador.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0028_reporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLicencia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('archivo', models.TextField(max_length=100, validators=[apps.reloj_fichador.models.validate_file_extension])),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o motivo de la licencia', null=True)),
                ('fecha_subida', models.DateField(blank=True, editable=False)),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio de la licencia', null=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin de la licencia', null=True)),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('aprobada', '✅ Aprobada'), ('rechazada', '❌ Rechazada')], default='pendiente', help_text='Estado de aprobación de la licencia', max_length=10)),
                ('aplicar_a_asistencia', models.BooleanField(default=True, help_text='Si está marcado, justificará automáticamente las ausencias en el período')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, help_text='Fecha y hora de aprobación/rechazo', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del aprobador', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical licencia',
                'verbose_name_plural': 'historical licencias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='licencia',
            name='aplicar_a_asistencia',
            field=models.BooleanField(default=True, help_text='Si está marcado, justificará automáticamente las ausencias en el período'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='aprobada_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que aprobó/rechazó la licencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('aprobada', '✅ Aprobada'), ('rechazada', '❌ Rechazada')], default='pendiente', help_text='Estado de aprobación de la licencia', max_length=10),
        ),
        migrations.AddField(
            model_name='licencia',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de aprobación/rechazo', null=True),
        ),
        migrations.AddField(
            model_name='licencia',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones del aprobador', null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='licencia_relacionada',
            field=models.ForeignKey(blank=True, help_text='Licencia que justifica esta ausencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reloj_fichador.licencia'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción o motivo de la licencia', null=True),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha de fin de la licencia', null=True),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio de la licencia', null=True),
        ),
        migrations.AddIndex(
            model_name='licencia',
            index=models.Index(fields=['operario', 'fecha_inicio'], name='reloj_ficha_operari_1b93a5_idx'),
        ),
        migrations.AddIndex(
            model_name='licencia',
            index=models.Index(fields=['estado'], name='reloj_ficha_estado_e0e337_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['operario', 'fecha'], name='reloj_ficha_operari_296cae_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['estado_asistencia', 'estado_justificacion'], name='reloj_ficha_estado__185074_idx'),
        ),
        migrations.AddField(
            model_name='historicallicencia',
            name='aprobada_por',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario que aprobó/rechazó la licencia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallicencia',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallicencia',
            name='operario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reloj_fichador.operario'),
        ),
    ]
