# Generated by Django 5.1.4 on 2025-06-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0028_configuracionredondeosalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionredondeo',
            name='minutos_redondeo_media',
            field=models.PositiveSmallIntegerField(default=35, help_text='Minutos máximos para redondear a la media hora. Ejemplo: con 45, 09:30 a 09:44 se redondea a 09:30.'),
        ),
    ]
