# Generated by Django 5.1.4 on 2025-08-11 18:29

import apps.reloj_fichador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0029_historicallicencia_licencia_aplicar_a_asistencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallicencia',
            name='archivo',
            field=models.TextField(blank=True, help_text='Archivo adjunto (opcional)', max_length=100, null=True, validators=[apps.reloj_fichador.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo adjunto (opcional)', null=True, upload_to='licencias/', validators=[apps.reloj_fichador.models.validate_file_extension]),
        ),
    ]
