# Generated by Django 5.1.4 on 2025-10-23 13:49

import apps.reloj_fichador.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0030_hacer_archivo_licencia_opcional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='estado',
            field=models.CharField(
                choices=[('pendiente', '⏳ Pendiente'), ('aprobada', '✅ Aprobada'), ('rechazada', '❌ Rechazada')],
                default='pendiente',
                help_text='Estado de aprobación de la licencia',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='licencia',
            name='aplicar_a_asistencia',
            field=models.BooleanField(
                default=True,
                help_text='Si está marcado, justificará automáticamente las ausencias en el período'
            ),
        ),
        migrations.AddField(
            model_name='licencia',
            name='aprobada_por',
            field=models.ForeignKey(
                blank=True,
                help_text='Usuario que aprobó/rechazó la licencia',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='licencia',
            name='fecha_aprobacion',
            field=models.DateTimeField(
                blank=True,
                help_text='Fecha y hora de aprobación/rechazo',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='licencia',
            name='observaciones',
            field=models.TextField(
                blank=True,
                help_text='Observaciones del aprobador',
                null=True
            ),
        ),
    ]
