# Generated by Django 5.1.4 on 2025-10-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0030_hacer_archivo_licencia_opcional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del día especial', unique=True)),
                ('tipo_dia', models.CharField(choices=[('laboral', '✅ Día Laboral Normal'), ('feriado', '🎉 Feriado Nacional'), ('feriado_movible', '📅 Feriado Movible'), ('paro', '✊ Paro/Conflicto Laboral'), ('mantenimiento', '🔧 Mantenimiento/Clausura'), ('otro', '❓ Otro')], default='laboral', help_text='Tipo de día especial', max_length=20)),
                ('nombre', models.CharField(help_text='Nombre del evento (ej: Día de la Independencia, Paro General)', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del evento', null=True)),
                ('aplica_a_todas_areas', models.BooleanField(default=True, help_text='Si está desmarcado, solo aplica a las áreas seleccionadas')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(blank=True, help_text='Áreas afectadas (si no aplica a todas)', to='reloj_fichador.area')),
            ],
            options={
                'verbose_name': 'Calendario Laboral',
                'verbose_name_plural': 'Calendarios Laborales',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['fecha'], name='reloj_ficha_fecha_233bfb_idx'), models.Index(fields=['tipo_dia'], name='reloj_ficha_tipo_di_ed8717_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrupoSabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('A', 'Grupo A - Semanas Pares'), ('B', 'Grupo B - Semanas Impares')], help_text='Grupo de sábado del operario', max_length=1)),
                ('fecha_inicio', models.DateField(help_text='Fecha desde la que tiene efecto esta asignación')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha hasta la que tiene efecto (NULL = indefinido)', null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Motivo del cambio de grupo (opcional)', null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('operario', models.ForeignKey(help_text='Operario asignado', on_delete=django.db.models.deletion.CASCADE, related_name='grupos_sabado', to='reloj_fichador.operario')),
            ],
            options={
                'verbose_name': 'Grupo de Sábado',
                'verbose_name_plural': 'Grupos de Sábado',
                'ordering': ['operario', '-fecha_inicio'],
                'indexes': [models.Index(fields=['operario', 'fecha_inicio'], name='reloj_ficha_operari_8c650c_idx'), models.Index(fields=['grupo'], name='reloj_ficha_grupo_6d5fea_idx')],
            },
        ),
    ]
