# Generated by Django 5.1.4 on 2025-10-23 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0032_add_calendario_laboral_y_grupo_sabado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaFeriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha sugerida del feriado')),
                ('nombre', models.CharField(help_text='Nombre del feriado (ej: Año Nuevo, Carnaval)', max_length=200)),
                ('tipo_sugerencia', models.CharField(choices=[('feriado_nacional', '🎉 Feriado Nacional'), ('feriado_movible', '📅 Feriado Movible'), ('otro', '❓ Otro')], default='otro', help_text='Tipo de feriado', max_length=20)),
                ('fuente', models.CharField(choices=[('api_argentina', 'API ArgentinaDatos'), ('manual', 'Ingresado Manualmente'), ('sistema', 'Sistema Automático')], default='api_argentina', help_text='De dónde proviene la sugerencia', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('aceptado', '✅ Aceptado'), ('rechazado', '❌ Rechazado'), ('revisado_despues', '🔄 Revisar Después')], default='pendiente', help_text='Estado actual de la sugerencia', max_length=20)),
                ('nota_admin', models.TextField(blank=True, help_text='Notas del administrador (ej: por qué se rechazó)', null=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesada', models.DateTimeField(blank=True, help_text='Fecha en que se procesó la sugerencia', null=True)),
                ('procesado_por', models.ForeignKey(blank=True, help_text='Usuario que procesó la sugerencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugerencia de Feriado',
                'verbose_name_plural': 'Sugerencias de Feriados',
                'ordering': ['estado', '-fecha_creada'],
                'indexes': [models.Index(fields=['fecha'], name='reloj_ficha_fecha_826a09_idx'), models.Index(fields=['estado'], name='reloj_ficha_estado_bc9a97_idx'), models.Index(fields=['fuente'], name='reloj_ficha_fuente_50b60a_idx')],
                'unique_together': {('fecha', 'fuente')},
            },
        ),
    ]
