# Generated by Django 5.1.4 on 2025-10-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0033_add_sugerencia_feriado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerenciaferiado',
            name='datos_fuente',
            field=models.JSONField(blank=True, help_text='Datos originales provistos por la fuente (JSON completo)', null=True),
        ),
        migrations.AddField(
            model_name='sugerenciaferiado',
            name='fuente_url',
            field=models.URLField(blank=True, help_text='URL desde donde se obtuvo la sugerencia', null=True),
        ),
    ]
