# Generated by Django 5.1.4 on 2025-10-23 18:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0033_add_sugerencia_feriado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_enfermedad', models.DurationField(default=datetime.timedelta, help_text='Horas de enfermedad de esta licencia (duracion × 8h)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mes_periodo', models.CharField(help_text='Mes al que corresponden estas horas (YYYY-MM)', max_length=20)),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reloj_fichador.licencia')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reloj_fichador.operario')),
            ],
            options={
                'verbose_name': 'Horas enfermedad',
                'verbose_name_plural': 'Horas enfermedad',
                'indexes': [models.Index(fields=['operario', 'mes_periodo'], name='reloj_ficha_operari_ad166a_idx'), models.Index(fields=['licencia'], name='reloj_ficha_licenci_f9d80b_idx')],
            },
        ),
    ]
