# Generated by Django 5.1.4 on 2025-11-11 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0034_add_horasenfermedade_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='horas_totales',
            name='horas_enfermedad',
            field=models.DurationField(default=datetime.timedelta, help_text='Horas acumuladas por licencias médicas aprobadas'),
        ),
        migrations.AddField(
            model_name='sugerenciaferiado',
            name='datos_fuente',
            field=models.JSONField(blank=True, help_text='Datos originales provistos por la fuente (JSON completo)', null=True),
        ),
        migrations.AddField(
            model_name='sugerenciaferiado',
            name='fuente_url',
            field=models.URLField(blank=True, help_text='URL desde donde se obtuvo la sugerencia', null=True),
        ),
        migrations.AlterField(
            model_name='gruposabado',
            name='grupo',
            field=models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B')], help_text='Grupo de sábado del operario', max_length=1),
        ),
    ]
