# Generated by Django 5.1.4 on 2026-02-11 14:19
# Manually adjusted: some indexes only existed in Django state, not in the actual DB.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reloj_fichador', '0035_horas_totales_horas_enfermedad_and_more'),
    ]

    operations = [
        # === ELIMINAR ÍNDICES REDUNDANTES ===

        # RegistroDiario: índice manual en operario_id es redundante (ya existe FK index).
        # Este SÍ existe en la BD real como 'reloj_ficha_operari_7b299b_idx'.
        migrations.RemoveIndex(
            model_name='registrodiario',
            name='reloj_ficha_operari_7b299b_idx',
        ),

        # Los siguientes índices existían en el código Python (models.Index) pero
        # NUNCA se crearon realmente en la BD (migraciones anteriores inconsistentes).
        # Usamos SeparateDatabaseAndState para actualizar solo el estado de Django
        # sin intentar DROP en la BD (lo que fallaría).

        # CalendarioLaboral: models.Index(fields=['fecha']) redundante con unique=True
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='calendariolaboral',
                    name='reloj_ficha_fecha_233bfb_idx',
                ),
            ],
            database_operations=[],
        ),

        # Operario: models.Index(fields=['dni']) redundante con unique=True
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='operario',
                    name='reloj_ficha_dni_b631b6_idx',
                ),
            ],
            database_operations=[],
        ),

        # RegistroAsistencia: models.Index(fields=['operario', 'fecha']) redundante con unique_together
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='registroasistencia',
                    name='reloj_ficha_operari_296cae_idx',
                ),
            ],
            database_operations=[],
        ),

        # HorasEnfermedad: models.Index(fields=['licencia']) redundante con ForeignKey
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='horasenfermedad',
                    name='reloj_ficha_licenci_f9d80b_idx',
                ),
            ],
            database_operations=[],
        ),

        # === CAMPOS ALTERADOS (detectados automáticamente por makemigrations) ===
        migrations.AlterField(
            model_name='historicallicencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('aprobada', '✅ Aprobada'), ('rechazada', '❌ Rechazada')], default='aprobada', help_text='Estado de aprobación de la licencia', max_length=10),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('aprobada', '✅ Aprobada'), ('rechazada', '❌ Rechazada')], default='aprobada', help_text='Estado de aprobación de la licencia', max_length=10),
        ),

        # === CREAR ÍNDICES COMPUESTOS NUEVOS ===

        # RegistroDiario: (operario_id, hora_fichada) - EL MÁS IMPORTANTE
        migrations.AddIndex(
            model_name='registrodiario',
            index=models.Index(fields=['operario', 'hora_fichada'], name='reloj_ficha_operari_95dca1_idx'),
        ),

        # Horas_trabajadas: (operario_id, fecha)
        migrations.AddIndex(
            model_name='horas_trabajadas',
            index=models.Index(fields=['operario', 'fecha'], name='reloj_ficha_operari_45f9bd_idx'),
        ),

        # Horas_totales: (operario_id, mes_actual)
        migrations.AddIndex(
            model_name='horas_totales',
            index=models.Index(fields=['operario', 'mes_actual'], name='reloj_ficha_operari_2e1411_idx'),
        ),

        # Horas_extras: (operario_id, fecha)
        migrations.AddIndex(
            model_name='horas_extras',
            index=models.Index(fields=['operario', 'fecha'], name='reloj_ficha_operari_ae6d68_idx'),
        ),

        # Horas_feriado: (operario_id, fecha)
        migrations.AddIndex(
            model_name='horas_feriado',
            index=models.Index(fields=['operario', 'fecha'], name='reloj_ficha_operari_c9b35a_idx'),
        ),
    ]
