services:
  db:
    image: mysql:8.4.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "53306:3306"
    networks:
      - app_network_fichador
    command: >
      --authentication_policy='*,,' --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: >
      /app/wait-for-it.sh db:3306 -t 120 -- bash -c "python manage.py collectstatic --noinput && gunicorn --workers 3 --timeout 120 --bind 0.0.0.0:58000 mantenedor.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./logs:/app/logs
    ports:
      - "58000:58000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=db
      - DB_PORT=3306
      - LANG=${LANG}
      - LANGUAGE=${LANGUAGE}
      - LC_ALL=${LC_ALL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    networks:
      - app_network_fichador

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: >
      /app/wait-for-it.sh db:3306 -t 120 -- bash -c "celery -A mantenedor worker --loglevel=info"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/5
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=db
      - LANG=${LANG}
      - LANGUAGE=${LANGUAGE}
      - LC_ALL=${LC_ALL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    networks:
      - app_network_fichador

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: >
      /app/wait-for-it.sh db:3306 -t 120 -- bash -c "celery -A mantenedor beat --loglevel=info"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/5
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=db
      - LANG=${LANG}
      - LANGUAGE=${LANGUAGE}
      - LC_ALL=${LC_ALL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    networks:
      - app_network_fichador

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6381:6379"
    networks:
      - app_network_fichador
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "5080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      web:
        condition: service_started
    networks:
      - app_network_fichador

  backup:
    image: mysql:8.4.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./backups:/backups
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./my_backup.cnf:/etc/my.cnf
    entrypoint: [ "/bin/sh", "-c", "if [ ! -f /root/.my.cnf ]; then echo '[client] user=$${MYSQL_USER} password=$${MYSQL_PASSWORD} host=db protocol=tcp' > /root/.my.cnf && chmod 600 /root/.my.cnf; fi && while true; do /wait-for-it.sh db:3306 -t 120 -- mysqldump -h db -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} --no-tablespaces $${MYSQL_DATABASE} > /backups/backup_$$(date +%F_%H.%M.%S).sql; echo 'Limpiando backups antiguos...'; cd /backups && ls -t *.sql | tail -n +481 | xargs -r rm -f; echo 'Limpieza completada. Se mantienen los 480 backups más recientes.'; sleep 1800; done" ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network_fichador

volumes:
  static_volume:
  media_volume:
  mysql_data:
  redis_data:


networks:
  app_network_fichador:
    driver: bridge
