services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'docker_horesdb'
      MYSQL_USER: 'Leandro'      
      MYSQL_PASSWORD: 'S1st3mas.1999'    
      MYSQL_ROOT_PASSWORD: 'S1st3mas.1999'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql      
           
    ports:
      - "53306:3306"  # Cambia a un puerto diferente para MySQL

  web:
    build: .
    restart: always
    command: gunicorn --workers 3 --bind 0.0.0.0:58000 mantenedor.wsgi:application
    volumes:
      - .:/app
    ports:
      - "58000:58000"  # Cambia el puerto expuesto para Gunicorn
    depends_on:
      - db
    environment:
      - DB_NAME=docker_horesdb
      - DB_USER=Leandro
      - DB_PASSWORD=S1st3mas.1999
      - DB_HOST=db
      - DB_PORT=3306

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "5080:80"  # Cambia el puerto expuesto para Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
