"""
Django settings for reloj_fichador project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import environ
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


SECRET_KEY = env('SECRET_KEY')

DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '192.168.10.11', ])

INSTALLED_APPS = [
    # Django Simpleui - Tema moderno para admin
    'simpleui',

    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps del proyecto
    'apps.reloj_fichador',
    'mantenedor',

    # Aplicaciones de terceros
    'crispy_forms',  # django-crispy-forms para mejora de formularios
    'crispy_bootstrap5',  # Template pack para crispy_forms
    'axes',  # django-axes para protección contra brute force
    'simple_history',
    'rangefilter',
    'django_celery_beat',
    'django_celery_results',
    'django_tables2',
    'import_export',
    'weasyprint',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'apps.reloj_fichador.middleware.TerminalCriticoMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    # Django-axes debe ir después de AuthenticationMiddleware
    'axes.middleware.AxesMiddleware',
    # Middlewares personalizados para manejo de errores
    'apps.reloj_fichador.middleware.PermissionMiddleware',
    'apps.reloj_fichador.middleware.ErrorHandlerMiddleware',
    # Middleware para desactivar cache en desarrollo
    'apps.reloj_fichador.middleware.DisableCacheMiddleware',
]

ROOT_URLCONF = 'mantenedor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Context processors personalizados
                'apps.reloj_fichador.context_processors.permissions',
            ],
        },
    },
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

WSGI_APPLICATION = 'mantenedor.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'",
            'charset': 'utf8mb4',
            'connect_timeout': 30,
            'autocommit': True,
            'isolation_level': 'READ COMMITTED',
        },
    }
}

# Authentication Backends (requerido por django-axes)
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # AxesStandaloneBackend debe ir primero
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

# Para mejor manejo de zonas horarias con Celery y django-celery-beat
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://redis:6379/5')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://redis:6379/5')
CELERY_BEAT_SCHEDULER = env('CELERY_BEAT_SCHEDULER', default='django_celery_beat.schedulers:DatabaseScheduler')

# Configuración para HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=True)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=True)
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'SAMEORIGIN'

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'https://localhost:5443',
    'https://192.168.0.228:5443',
    'https://192.168.10.11:5443',
    'https://192.168.10.12:5443',
    'https://192.168.10.18:5443',
    'https://192.168.10.8:5443',
    'https://192.168.10.4:5443',
    'https://192.168.10.13:5443',
    'https://192.168.10.43:5443',
    'https://192.168.10.17:5443',
])

# Configuraciones adicionales para sesiones y CSRF
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 días para terminal de fichaje
CSRF_COOKIE_AGE = 60 * 60 * 24 * 30     # 30 días

# Nombre de cookie personalizado para evitar conflictos
SESSION_COOKIE_NAME = "fichador_session"
CSRF_COOKIE_NAME = "fichador_csrf"

# Almacenar el token CSRF en la sesión para máxima disponibilidad
CSRF_USE_SESSIONS = True

# Guardar la sesión en cada solicitud para prolongar su duración
SESSION_SAVE_EVERY_REQUEST = True

# Configuración de cookies para entorno seguro
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Configuración para permitir acceso JavaScript al CSRF token si es necesario
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = True  # Proteger la sesión

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message} - IP: {ip}',
            'style': '{',
        },
        'request_info': {
            'format': '{levelname} {asctime} {module} {message} - IP: {ip} - Host: {host} - User-Agent: {agent}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'add_client_info': {
            '()': 'apps.reloj_fichador.filters.ClientInfoFilter',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['add_client_info'],
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django.log'),
            'formatter': 'verbose',
            'filters': ['add_client_info'],
        },
        'request_log': {
            'level': 'INFO', 
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/requests.log'),
            'formatter': 'request_info',
            'filters': ['add_client_info'],
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'reloj_fichador': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['request_log', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Configuración especial para las pruebas
if 'test' in sys.argv:
    print("Usando SQLite en memoria para las pruebas")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']
    DEBUG = False

# ============================================================================
# CONFIGURACIÓN DE DJANGO-AXES (Protección contra Brute Force)
# ============================================================================

# Número máximo de intentos de login fallidos antes de bloquear
AXES_FAILURE_LIMIT = 5

# Tiempo de bloqueo después de exceder el límite (en minutos)
from datetime import timedelta
AXES_COOLOFF_TIME = timedelta(minutes=15)

# Usar IP + username para rastrear intentos (más seguro)
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]

# Mensaje personalizado cuando se bloquea al usuario
AXES_LOCKOUT_TEMPLATE = 'errors/429.html'  # Template personalizado en español
AXES_VERBOSE = True  # Habilitar logs detallados

# Solo bloquear en el admin login
AXES_ONLY_ADMIN_SITE = True

# Reiniciar intentos después del cooloff
AXES_RESET_ON_SUCCESS = True

# Usar cache de Django (Redis) para almacenar intentos
AXES_CACHE = 'default'

# Habilitar integración con Django admin para ver intentos bloqueados
AXES_ENABLE_ADMIN = True

# No bloquear IPs de la whitelist (opcional, comentado por ahora)
# AXES_NEVER_LOCKOUT_WHITELIST = True
# AXES_IP_WHITELIST = ['127.0.0.1', '172.19.0.2']

# Lockout por IP o por usuario+IP (más seguro: usuario+IP)
# AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True  # DEPRECADO en versión 6.x
# En su lugar, usar AXES_LOCKOUT_PARAMETERS arriba configurado como [["username", "ip_address"]]

# ============================================================================
# CONFIGURACIÓN DE REDIRECCIONES DE LOGIN/LOGOUT
# ============================================================================

# Redirigir al admin después de login exitoso
LOGIN_REDIRECT_URL = '/admin/'

# Redirigir al login después de logout
LOGOUT_REDIRECT_URL = '/admin/login/'

# URL de login (usado por @login_required decorator)
LOGIN_URL = '/admin/login/'

# ============================================================================
# CONFIGURACIÓN DE DJANGO-CRISPY-FORMS
# ============================================================================

CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_ALLOWED_TEMPLATE_PACKS = ["bootstrap5"]

# ============================================================================
# CONFIGURACIÓN DE DJANGO-SIMPLEUI - ICONOS
# ============================================================================

# Configuración de iconos para el menú del admin
# Los iconos utilizan FontAwesome 6 (incluido en Simpleui)
# Documentación: https://fontawesome.com/icons
SIMPLEUI_ICON = {
    # Modelos principales del sistema de fichaje
    'operarios': 'fas fa-users',  # Empleados/Personal
    'registro diarios': 'fas fa-clock',  # Registros de entrada/salida
    'Horas trabajadas': 'fas fa-business-time',  # Horas de trabajo
    'Horas extras': 'fas fa-clock-rotate-left',  # Horas extras
    'Horas totales': 'fas fa-calculator',  # Cálculo de totales
    'Horas feriado': 'fas fa-umbrella-beach',  # Días feriados
    'Horas enfermedad': 'fas fa-notes-medical',  # Licencias médicas
    'registro asistencias': 'fas fa-clipboard-check',  # Control de asistencia

    # Configuración de horarios y áreas
    'horarios': 'fas fa-calendar-alt',  # Horarios de trabajo
    'areas': 'fas fa-building',  # Áreas/Departamentos
    'licencias': 'fas fa-file-medical',  # Licencias y permisos
    'Calendarios Laborales': 'fas fa-calendar',  # Calendario laboral
    'Grupos de Sábado': 'fas fa-calendar-week',  # Grupos de sábado
    'Sugerencias de Feriados': 'fas fa-lightbulb',  # Sugerencias

    # Reportes y análisis
    '📊 Reportes': 'fas fa-chart-line',  # Reportes estadísticos

    # Configuración del sistema
    'Configuración de Redondeo': 'fas fa-cog',  # Configuración entrada
    'Configuración de Redondeo de Salida': 'fas fa-cogs',  # Configuración salida

    # Usuarios y permisos (Django Auth)
    'usuarios': 'fas fa-user',  # Usuarios del sistema
    'grupos': 'fas fa-users-cog',  # Grupos y permisos

    # Auditoría e historial
    'Registros de auditoría': 'fas fa-history',  # Logs del sistema
    'historical operarios': 'fas fa-history',  # Histórico de operarios
    'historical registro diarios': 'fas fa-history',  # Histórico de registros
    'historical licencias': 'fas fa-history',  # Histórico de licencias
}

# Configuración adicional de Simpleui
SIMPLEUI_HOME_TITLE = 'Sistema de Control de Asistencia'  # Título de la página de inicio
SIMPLEUI_HOME_ICON = 'fas fa-home'  # Icono de inicio
SIMPLEUI_LOGO = '/static/images/logo_hores.png'  # Logo personalizado
